-- DROP TABLE IF EXISTS ENVIRONMENT CASCADE;

-- CREATE TABLE IF NOT EXISTS ENVIRONMENT
-- (
--     ID           SMALLSERIAL         NOT NULL,
--     NAME         VARCHAR(20)         NOT NULL UNIQUE,
--     ROOTINSTANCE VARCHAR(10)         NOT NULL UNIQUE,
--     ISACTIVE     BOOLEAN DEFAULT '1' NOT NULL,
--     PRIMARY KEY (ID)
--     );
